-- Revert if exists to ensure clean state
DROP TABLE IF EXISTS public.faithful_clients CASCADE;

-- Create faithful_clients table
CREATE TABLE public.faithful_clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    full_name text NOT NULL,
    cin text NOT NULL,
    phone text NOT NULL,
    email text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.faithful_clients ENABLE ROW LEVEL SECURITY;

-- Create permissive policies because authentication is handled at application level
-- and Supabase connection uses anonymous key.

CREATE POLICY "Enable read access for all users" ON public.faithful_clients
    FOR SELECT
    USING (true);

CREATE POLICY "Enable insert for all users" ON public.faithful_clients
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON public.faithful_clients
    FOR UPDATE
    USING (true);

CREATE POLICY "Enable delete for all users" ON public.faithful_clients
    FOR DELETE
    USING (true);

-- Add indexes for search performance
CREATE INDEX idx_faithful_clients_tenant_id ON public.faithful_clients(tenant_id);
CREATE INDEX idx_faithful_clients_name ON public.faithful_clients USING btree (full_name);
CREATE INDEX idx_faithful_clients_cin ON public.faithful_clients USING btree (cin);
