-- ============================================================================
-- COMPLETE SUPABASE SETUP FOR GS CARS
-- ============================================================================
-- This script sets up the entire database schema, functions, triggers, and policies.
-- WARNING: This will DROP existing tables and data to ensure a clean slate.
-- Run this in the Supabase SQL Editor.
-- ============================================================================

-- 1. CLEANUP (Drop existing objects)
-- ============================================================================
-- 1. CLEANUP (Drop existing objects)
-- ============================================================================
-- Note: Dropping tables with CASCADE automatically drops their triggers, policies, and indexes.

DROP FUNCTION IF EXISTS update_single_car_status() CASCADE;
DROP FUNCTION IF EXISTS auto_update_car_status() CASCADE;
DROP FUNCTION IF EXISTS check_car_has_active_reservation(bigint) CASCADE;
DROP FUNCTION IF EXISTS update_car_mileage_from_maintenance() CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP FUNCTION IF EXISTS set_reservation_number() CASCADE;
DROP FUNCTION IF EXISTS generate_reservation_number() CASCADE;

DROP TABLE IF EXISTS public.reservation_documents CASCADE;
DROP TABLE IF EXISTS public.maintenance_records CASCADE;
DROP TABLE IF EXISTS public.reservations CASCADE;
DROP TABLE IF EXISTS public.cars CASCADE;

-- 2. TABLES
-- ============================================================================

-- Table: cars
CREATE TABLE public.cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    make TEXT NOT NULL,  -- e.g. Renault
    model TEXT NOT NULL, -- e.g. Clio
    brand TEXT,          -- added for stricter checking if needed, or alias for make
    year INTEGER NOT NULL,
    license_plate TEXT NOT NULL,
    color TEXT NOT NULL,
    price_per_day NUMERIC NOT NULL,
    mileage INTEGER NOT NULL DEFAULT 0,
    transmission TEXT NOT NULL,
    seats INTEGER NOT NULL,
    fuel_type TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'disponible',
    image_url TEXT,
    auto_manage_status BOOLEAN DEFAULT true,

    -- Constraints
    CONSTRAINT cars_status_check CHECK (status IN ('disponible', 'loue', 'maintenance')),
    CONSTRAINT cars_plate_number_unique UNIQUE (license_plate)
);

-- Table: reservations
CREATE TABLE public.reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_number VARCHAR(20) UNIQUE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Link to Supabase Auth User

    -- Client Information
    client_name VARCHAR(255) NOT NULL,
    client_cin VARCHAR(50) NOT NULL,
    client_phone VARCHAR(50) NOT NULL,
    client_email VARCHAR(255),

    -- Reservation Details
    car_id BIGINT REFERENCES public.cars(id) ON DELETE RESTRICT NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    pickup_time TIME,
    return_time TIME,
    pickup_location VARCHAR(255),
    return_location VARCHAR(255),
    
    -- Calculations
    duration_days INTEGER NOT NULL,
    price_per_day NUMERIC(10, 2) NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    
    -- Status
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'active', 'completed', 'cancelled')),
    
    -- Metadata
    notes TEXT,
    cancellation_reason TEXT,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for reservations
CREATE INDEX idx_reservation_number ON public.reservations(reservation_number);
CREATE INDEX idx_reservations_car_id ON public.reservations(car_id);
CREATE INDEX idx_reservations_user_id ON public.reservations(user_id);
CREATE INDEX idx_reservations_dates ON public.reservations(start_date, end_date);
CREATE INDEX idx_reservations_status ON public.reservations(status);


-- Table: maintenance_records
CREATE TABLE public.maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    car_id BIGINT REFERENCES public.cars(id) ON DELETE CASCADE NOT NULL,
    
    maintenance_type TEXT NOT NULL CHECK (maintenance_type IN ('OIL_CHANGE', 'BRAKE_SERVICE', 'REPAIR', 'ROUTINE_CHECK')),
    cost NUMERIC(10, 2) NOT NULL DEFAULT 0,
    odometer INTEGER NOT NULL,
    next_due_mileage INTEGER, -- For tracking next oil change etc.
    maintenance_date DATE NOT NULL,
    notes TEXT,
    provider TEXT,
    
    CONSTRAINT maintenance_records_car_id_idx UNIQUE (id, car_id)
);

CREATE INDEX idx_maintenance_records_car_id ON public.maintenance_records(car_id);
CREATE INDEX idx_maintenance_records_date ON public.maintenance_records(maintenance_date DESC);


-- Table: reservation_documents
CREATE TABLE public.reservation_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reservation_id BIGINT REFERENCES public.reservations(id) ON DELETE CASCADE NOT NULL,
    file_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT now() NOT NULL
);


-- 3. FUNCTIONS & TRIGGERS
-- ============================================================================

-- Function: Generate Reservation Number
CREATE OR REPLACE FUNCTION generate_reservation_number()
RETURNS TEXT AS $$
DECLARE
    new_number TEXT;
    exists_check INTEGER;
BEGIN
    LOOP
        new_number := 'RES-' || UPPER(LEFT(MD5(RANDOM()::TEXT), 7));
        SELECT COUNT(*) INTO exists_check FROM reservations WHERE reservation_number = new_number;
        EXIT WHEN exists_check = 0;
    END LOOP;
    RETURN new_number;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Set Reservation Number
CREATE OR REPLACE FUNCTION set_reservation_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.reservation_number IS NULL OR NEW.reservation_number = '' THEN
        NEW.reservation_number := generate_reservation_number();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_reservation_number
    BEFORE INSERT ON reservations
    FOR EACH ROW
    EXECUTE FUNCTION set_reservation_number();

-- Trigger: Update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_reservation_timestamp
    BEFORE UPDATE ON reservations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- Feature: Auto-Update Car Mileage from Maintenance
CREATE OR REPLACE FUNCTION update_car_mileage_from_maintenance()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.cars
    SET mileage = NEW.odometer
    WHERE id = NEW.car_id
    AND (mileage IS NULL OR mileage < NEW.odometer);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_car_mileage
    AFTER INSERT OR UPDATE ON public.maintenance_records
    FOR EACH ROW
    EXECUTE FUNCTION update_car_mileage_from_maintenance();


-- Feature: Auto-Update Car Status based on Reservations
CREATE OR REPLACE FUNCTION check_car_has_active_reservation(car_id_param BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
    has_active BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 
        FROM public.reservations 
        WHERE car_id = car_id_param 
        AND status IN ('pending', 'confirmed', 'active')
        AND start_date <= CURRENT_DATE 
        AND end_date >= CURRENT_DATE
    ) INTO has_active;
    RETURN has_active;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_single_car_status()
RETURNS TRIGGER AS $$
DECLARE
    target_car_id BIGINT;
    car_auto_manage BOOLEAN;
    new_status TEXT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_car_id := OLD.car_id;
    ELSE
        target_car_id := NEW.car_id;
    END IF;
    
    SELECT auto_manage_status INTO car_auto_manage FROM public.cars WHERE id = target_car_id;
    
    IF car_auto_manage THEN
        IF check_car_has_active_reservation(target_car_id) THEN
            new_status := 'loue';
        ELSE
            new_status := 'disponible';
        END IF;
        
        UPDATE public.cars SET status = new_status WHERE id = target_car_id;
    END IF;
    
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_car_status_on_reservation_change
    AFTER INSERT OR UPDATE OR DELETE ON public.reservations
    FOR EACH ROW
    EXECUTE FUNCTION update_single_car_status();


-- 4. ROW LEVEL SECURITY (RLS)
-- ============================================================================
-- Enabling RLS on all tables
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_documents ENABLE ROW LEVEL SECURITY;

-- PERMISSIVE POLICIES (Allow all for now, as requested)
-- Ideally this should be restricted to authenticated users/admins later.

-- Cars
CREATE POLICY "Allow public read cars" ON public.cars FOR SELECT USING (true);
CREATE POLICY "Allow auth operations cars" ON public.cars FOR ALL USING (auth.role() = 'authenticated');

-- Reservations (Permissive as per latest migration)
CREATE POLICY "Allow all select reservations" ON public.reservations FOR SELECT USING (true);
CREATE POLICY "Allow all insert reservations" ON public.reservations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update reservations" ON public.reservations FOR UPDATE USING (true);
CREATE POLICY "Allow all delete reservations" ON public.reservations FOR DELETE USING (true);

-- Maintenance Records
CREATE POLICY "Allow all maintenance read" ON public.maintenance_records FOR SELECT USING (true);
CREATE POLICY "Allow all maintenance insert" ON public.maintenance_records FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all maintenance update" ON public.maintenance_records FOR UPDATE USING (true);
CREATE POLICY "Allow all maintenance delete" ON public.maintenance_records FOR DELETE USING (true);

-- Reservation Documents
CREATE POLICY "Allow all doc read" ON public.reservation_documents FOR SELECT USING (true);
CREATE POLICY "Allow all doc insert" ON public.reservation_documents FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all doc delete" ON public.reservation_documents FOR DELETE USING (true);


-- 5. STORAGE BUCKETS
-- ============================================================================
-- Attempt to create buckets. If this fails (permissions), users must create manually.

-- Car Images Bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('car-images', 'car-images', true) ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Images Public Read" ON storage.objects;
CREATE POLICY "Images Public Read" ON storage.objects FOR SELECT USING (bucket_id = 'car-images');

DROP POLICY IF EXISTS "Images Auth Upload" ON storage.objects;
CREATE POLICY "Images Auth Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'car-images' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Images Auth Delete" ON storage.objects;
CREATE POLICY "Images Auth Delete" ON storage.objects FOR DELETE USING (bucket_id = 'car-images' AND auth.role() = 'authenticated');

-- Contracts Bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('contracts', 'contracts', true) ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Contracts Public Upload" ON storage.objects;
CREATE POLICY "Contracts Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'contracts');

DROP POLICY IF EXISTS "Contracts Public Read" ON storage.objects;
CREATE POLICY "Contracts Public Read" ON storage.objects FOR SELECT USING (bucket_id = 'contracts');

DROP POLICY IF EXISTS "Contracts Auth Delete" ON storage.objects;
CREATE POLICY "Contracts Auth Delete" ON storage.objects FOR DELETE USING (bucket_id = 'contracts' AND auth.role() = 'authenticated');

-- ============================================================================
-- END OF SETUP
-- ============================================================================
