-- ============================================================
-- Planned Reservations (Agenda) — tenant-scoped
-- ------------------------------------------------------------
-- Backs the page /admin/agenda where staff plan future / potential
-- reservations before they become real ones. Backed by the composable
-- useAgenda.
--
-- Run once in the Supabase SQL editor.
-- ============================================================

-- Idempotent table creation
CREATE TABLE IF NOT EXISTS public.planned_reservations (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        uuid REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    client_name      text NOT NULL,
    client_phone     text,                -- optionnel
    start_date       date NOT NULL,       -- début de la période prévue (Du)
    end_date         date,                -- fin de la période prévue (Au)
    price_per_day    numeric,             -- prix par jour estimé (DT)
    pickup_location  text,                -- lieu de prise du véhicule
    return_location  text,                -- lieu de remise du véhicule
    car_note         text,                -- type de voiture souhaité (auto/manuelle, grande/petite...)
    created_at       timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Upgrade path: if a previous version created this table with a single
-- `reservation_date` column, migrate it to the start_date / end_date period.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'planned_reservations'
                 AND column_name = 'reservation_date')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'planned_reservations'
                 AND column_name = 'start_date') THEN
        ALTER TABLE public.planned_reservations RENAME COLUMN reservation_date TO start_date;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'planned_reservations'
                 AND column_name = 'end_date') THEN
        ALTER TABLE public.planned_reservations ADD COLUMN end_date date;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'planned_reservations'
                 AND column_name = 'price_per_day') THEN
        ALTER TABLE public.planned_reservations ADD COLUMN price_per_day numeric;
    END IF;
END $$;

-- Enable Row Level Security
ALTER TABLE public.planned_reservations ENABLE ROW LEVEL SECURITY;

-- Permissive policies (auth is enforced at the application layer,
-- consistent with b2b_clients / reported_clients / faithful_clients).
DROP POLICY IF EXISTS "Enable read access for all users"   ON public.planned_reservations;
DROP POLICY IF EXISTS "Enable insert for all users"        ON public.planned_reservations;
DROP POLICY IF EXISTS "Enable update for all users"        ON public.planned_reservations;
DROP POLICY IF EXISTS "Enable delete for all users"        ON public.planned_reservations;

CREATE POLICY "Enable read access for all users" ON public.planned_reservations
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON public.planned_reservations
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON public.planned_reservations
    FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON public.planned_reservations
    FOR DELETE USING (true);

-- Indexes for common access patterns
CREATE INDEX IF NOT EXISTS idx_planned_reservations_tenant_id  ON public.planned_reservations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_planned_reservations_start_date ON public.planned_reservations(start_date);
CREATE INDEX IF NOT EXISTS idx_planned_reservations_name       ON public.planned_reservations USING btree (client_name);
