-- ============================================================
-- B2B Chauffeurs — drivers belonging to a B2B client (agency)
-- ------------------------------------------------------------
-- Each B2B client (agency) owns a list of chauffeurs. Backs the
-- "Chauffeurs" manager on /admin/services/b2b-clients and the
-- composable useB2BChauffeurs.
--
-- Run once in the Supabase SQL editor. Rows are deleted automatically
-- when their parent agency (or tenant) is removed (ON DELETE CASCADE).
-- ============================================================

-- Idempotent table creation
CREATE TABLE IF NOT EXISTS public.b2b_chauffeurs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    b2b_client_id   bigint REFERENCES public.b2b_clients(id) ON DELETE CASCADE NOT NULL,
    nom             text NOT NULL,
    prenom          text,
    permit_number   text,           -- N° permis de conduire
    cin             text,           -- CIN / Passeport
    created_at      timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.b2b_chauffeurs ENABLE ROW LEVEL SECURITY;

-- Permissive policies (auth is enforced at the application layer,
-- consistent with b2b_clients / reported_clients / faithful_clients).
DROP POLICY IF EXISTS "Enable read access for all users"   ON public.b2b_chauffeurs;
DROP POLICY IF EXISTS "Enable insert for all users"        ON public.b2b_chauffeurs;
DROP POLICY IF EXISTS "Enable update for all users"        ON public.b2b_chauffeurs;
DROP POLICY IF EXISTS "Enable delete for all users"        ON public.b2b_chauffeurs;

CREATE POLICY "Enable read access for all users" ON public.b2b_chauffeurs
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON public.b2b_chauffeurs
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON public.b2b_chauffeurs
    FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON public.b2b_chauffeurs
    FOR DELETE USING (true);

-- Indexes for common access patterns
CREATE INDEX IF NOT EXISTS idx_b2b_chauffeurs_tenant_id ON public.b2b_chauffeurs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_b2b_chauffeurs_client_id ON public.b2b_chauffeurs(b2b_client_id);
