-- ============================================================
-- B2B Clients (Agencies / Corporate clients) — tenant-scoped
-- ------------------------------------------------------------
-- Backs the page /admin/services/b2b-clients and the composable
-- useB2BClients. Required columns are exactly what the
-- "Nouveau Client B2B" modal sends.
-- ============================================================

-- Idempotent table creation
CREATE TABLE IF NOT EXISTS public.b2b_clients (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       uuid REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    company_name    text NOT NULL,
    contact_name    text,
    address         text,
    mf              text,           -- Matricule Fiscal
    phone           text,
    email           text,
    notes           text,
    created_at      timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.b2b_clients ENABLE ROW LEVEL SECURITY;

-- Permissive policies (auth is enforced at the application layer,
-- consistent with reported_clients / faithful_clients).
DROP POLICY IF EXISTS "Enable read access for all users"   ON public.b2b_clients;
DROP POLICY IF EXISTS "Enable insert for all users"        ON public.b2b_clients;
DROP POLICY IF EXISTS "Enable update for all users"        ON public.b2b_clients;
DROP POLICY IF EXISTS "Enable delete for all users"        ON public.b2b_clients;

CREATE POLICY "Enable read access for all users" ON public.b2b_clients
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON public.b2b_clients
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON public.b2b_clients
    FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON public.b2b_clients
    FOR DELETE USING (true);

-- Indexes for common access patterns
CREATE INDEX IF NOT EXISTS idx_b2b_clients_tenant_id    ON public.b2b_clients(tenant_id);
CREATE INDEX IF NOT EXISTS idx_b2b_clients_company_name ON public.b2b_clients USING btree (company_name);
