-- Create cars table
create table public.cars (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  make text not null,
  model text not null,
  year integer not null,
  license_plate text not null,
  color text not null,
  price_per_day numeric not null,
  mileage numeric not null,
  transmission text not null,
  seats integer not null,
  fuel_type text not null,
  description text,
  status text default 'available'::text,
  image_url text
);

-- Create reservations table
create table public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  reservation_number text not null,
  user_id uuid references auth.users not null,
  car_id bigint references public.cars not null,
  start_date date not null,
  end_date date not null,
  pickup_time time,
  return_time time,
  pickup_location text,
  return_location text,
  total_days integer not null,
  daily_rate numeric not null,
  subtotal numeric not null,
  tax_amount numeric not null,
  discount_amount numeric default 0,
  total_amount numeric not null,
  status text default 'pending'::text,
  notes text,
  cancellation_reason text,
  cancelled_at timestamp with time zone
);

-- Enable Row Level Security
alter table public.cars enable row level security;
alter table public.reservations enable row level security;

-- Policies for cars
create policy "Public cars are viewable by everyone"
  on public.cars for select
  using ( true );

create policy "Admins can insert cars"
  on public.cars for insert
  with check ( auth.role() = 'authenticated' ); -- Ideally check for admin role

create policy "Admins can update cars"
  on public.cars for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete cars"
  on public.cars for delete
  using ( auth.role() = 'authenticated' );

-- Policies for reservations
create policy "Users can view their own reservations"
  on public.reservations for select
  using ( auth.uid() = user_id );

create policy "Admins can view all reservations"
  on public.reservations for select
  using ( auth.role() = 'authenticated' ); -- Adjust for admin check

create policy "Users can create reservations"
  on public.reservations for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own reservations"
  on public.reservations for update
  using ( auth.uid() = user_id );

-- Storage Bucket for Car Images
insert into storage.buckets (id, name, public)
values ('car-images', 'car-images', true);

create policy "Car images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'car-images' );

create policy "Authenticated users can upload car images"
  on storage.objects for insert
  with check ( bucket_id = 'car-images' and auth.role() = 'authenticated' );
