-- Fleet Maintenance Records Migration
-- Run this in Supabase SQL Editor

-- Create maintenance_records table
CREATE TABLE IF NOT EXISTS public.maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Foreign key to cars table
    car_id BIGINT REFERENCES public.cars(id) ON DELETE CASCADE NOT NULL,
    
    -- Maintenance details
    maintenance_type TEXT NOT NULL CHECK (maintenance_type IN ('OIL_CHANGE', 'BRAKE_SERVICE', 'REPAIR', 'ROUTINE_CHECK')),
    cost NUMERIC(10, 2) NOT NULL DEFAULT 0,
    odometer INTEGER NOT NULL,
    maintenance_date DATE NOT NULL,
    notes TEXT,
    provider TEXT,
    
    -- Indexes for better query performance
    CONSTRAINT maintenance_records_car_id_idx UNIQUE (id, car_id)
);

-- Create index on car_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_maintenance_records_car_id ON public.maintenance_records(car_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_date ON public.maintenance_records(maintenance_date DESC);

-- Enable Row Level Security
ALTER TABLE public.maintenance_records ENABLE ROW LEVEL SECURITY;

-- Policies for maintenance_records
-- Allow all read access (since admin auth is separate from Supabase)
CREATE POLICY "Allow all to view maintenance records"
    ON public.maintenance_records FOR SELECT
    USING (true);

-- Allow all insert access
CREATE POLICY "Allow all to insert maintenance records"
    ON public.maintenance_records FOR INSERT
    WITH CHECK (true);

-- Allow all update access
CREATE POLICY "Allow all to update maintenance records"
    ON public.maintenance_records FOR UPDATE
    USING (true);

-- Allow all delete access
CREATE POLICY "Allow all to delete maintenance records"
    ON public.maintenance_records FOR DELETE
    USING (true);

-- Function to update car mileage when maintenance record is created/updated
CREATE OR REPLACE FUNCTION update_car_mileage_from_maintenance()
RETURNS TRIGGER AS $$
BEGIN
    -- Update car's mileage if the maintenance odometer is higher
    UPDATE public.cars
    SET mileage = NEW.odometer
    WHERE id = NEW.car_id
    AND (mileage IS NULL OR mileage < NEW.odometer);
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update car mileage
DROP TRIGGER IF EXISTS trigger_update_car_mileage ON public.maintenance_records;
CREATE TRIGGER trigger_update_car_mileage
    AFTER INSERT OR UPDATE ON public.maintenance_records
    FOR EACH ROW
    EXECUTE FUNCTION update_car_mileage_from_maintenance();

-- Add mileage column to cars table if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'cars' AND column_name = 'mileage'
    ) THEN
        ALTER TABLE public.cars ADD COLUMN mileage INTEGER DEFAULT 0;
    END IF;
END $$;
