-- Create store_apps table
create table public.store_apps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric(10, 2) default 0,
  icon_url text,
  is_active boolean default true
);

-- RLS Policies
alter table public.store_apps enable row level security;

-- Everyone can read active apps
create policy "Enable read access for all users"
on public.store_apps for select
using (true);

-- Only authenticated users can insert/update/delete (Validation handled in app/backend logic often, 
-- but ideally we restrict to specific internal users. 
-- For now allowing authenticated but we will protect via UI/API logic or specific user UUIDs if known)
-- Better: Use a specific policy if we have a way to identify Root. 
-- Assuming 'authenticated' for now, relying on app logic to only expose management to Super Admin.
create policy "Enable write access for authenticated users"
on public.store_apps for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- Storage Bucket for App Icons (if not exists)
insert into storage.buckets (id, name, public)
values ('store-icons', 'store-icons', true)
on conflict (id) do nothing;

create policy "Give public access to store icons"
on storage.objects for select
using ( bucket_id = 'store-icons' );

create policy "Enable upload access to auth users"
on storage.objects for insert
with check ( bucket_id = 'store-icons' and auth.role() = 'authenticated' );
