-- Create table for App Assignments
create table public.app_assignments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  app_id bigint references public.store_apps(id) on delete cascade not null,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  assigned_by uuid references auth.users(id), -- Optional: track who assigned it
  status text default 'active',
  
  -- Prevent duplicate assignments
  unique(app_id, tenant_id)
);

-- Enable RLS
alter table public.app_assignments enable row level security;

-- Policy: Root Admins can view/edit everything.
-- For now, since we use custom admin auth or direct Supabase client in root dashboard,
-- we'll allow public access/insert if authenticated as a workaround (similar to store_apps).
-- Ideally, this should be restricted to specific roles.

create policy "Public read assignments"
on public.app_assignments for select
using (true);

create policy "Public insert assignments"
on public.app_assignments for insert
with check (true);

create policy "Public delete assignments"
on public.app_assignments for delete
using (true);
