-- DROP existing table to clean up any schema mismatches or old policies
drop table if exists public.store_apps cascade;

-- Re-create table for Global Store (No tenant_id requirement)
create table public.store_apps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric(10, 2) default 0,
  icon_url text,
  is_active boolean default true
);

-- Enable RLS
alter table public.store_apps enable row level security;

-- Policy: Everyone can read active apps (Public/Anon/Auth)
create policy "Public read access"
on public.store_apps for select
using (true);

-- Policy: Allow Public Insert (Workaround for Custom Admin Auth which is not Supabase Auth)
create policy "Public insert access"
on public.store_apps for insert
with check (true);

-- Policy: Allow Public Update
create policy "Public update access"
on public.store_apps for update
using (true);

-- Policy: Allow Public Delete
create policy "Public delete access"
on public.store_apps for delete
using (true);


-- Ensure Storage Bucket Exists
insert into storage.buckets (id, name, public)
values ('store-icons', 'store-icons', true)
on conflict (id) do nothing;

-- Fix Storage Policies (Drop old ones if they exist to avoid conflict, or use idempotent)
drop policy if exists "Give public access to store icons" on storage.objects;
create policy "Give public access to store icons"
on storage.objects for select
using ( bucket_id = 'store-icons' );

drop policy if exists "Enable upload access to auth users" on storage.objects;
create policy "Enable upload access to auth users"
on storage.objects for insert
with check ( bucket_id = 'store-icons' and auth.role() = 'authenticated' );
